<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="3" passed="2" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-17T16:51:59 IST" name="Default suite" finished-at="2024-04-17T16:51:59 IST" duration-ms="79">
    <groups>
      <group name="sanity">
        <method signature="day1.personalloan()[pri:1, instance:rahulShettyTestng.day1@54d9d12d]" name="personalloan" class="rahulShettyTestng.day1"/>
        <method signature="day1.setuppppp()[pri:2, instance:rahulShettyTestng.day1@54d9d12d]" name="setuppppp" class="rahulShettyTestng.day1"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2024-04-17T16:51:59 IST" name="Default test" finished-at="2024-04-17T16:51:59 IST" duration-ms="79">
      <class name="rahulShettyTestng.day1">
        <test-method signature="personalloan()[pri:1, instance:rahulShettyTestng.day1@54d9d12d]" started-at="2024-04-17T16:51:59 IST" name="personalloan" finished-at="2024-04-17T16:51:59 IST" duration-ms="15" status="PASS">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at rahulShettyTestng.day1.personalloan(day1.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- personalloan -->
        <test-method signature="setuppppp()[pri:2, instance:rahulShettyTestng.day1@54d9d12d]" started-at="2024-04-17T16:51:59 IST" name="setuppppp" finished-at="2024-04-17T16:51:59 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setuppppp -->
      </class> <!-- rahulShettyTestng.day1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
